### PR TITLE
feat: Allow sampling in the backgound

### LINKED ISSUE #90: After chains in warmup go to zero, show how many chains are still sampling instead

### PR DESCRIPTION
**Pull request by aseyboldt**
Allow sampling in the background:

```python
import pymc as pm
import nutpie

with pm.Model() as model:
    pm.Normal("x", shape=10_000)

compiled = nutpie.compile_pymc_model(model)

sampler = nutpie.sample(compiled, blocking=False)

try:
    sampler.wait(timeout=2)
except TimeoutError:
    pass

#sampler.abort()
trace = sampler.finalize()
```

cc @ricardoV94 

Also fixes #90

### CODE REVIEW

**Review by ricardoV94 — APPROVED** [review]
Neat

**Comment by ricardoV94** [comment]
Is there a way to probe if the sampling is finished without interrupting or blocking? Not clear from skimming the code

**Comment by aseyboldt** [comment]
> Is there a way to probe if the sampling is finished without interrupting or blocking? Not clear from skimming the code

Now there is a `is_finished` property...

**Comment by aseyboldt** [comment]
And now also `sampler.pause()` and `sampler.resume()` and `sampler.wait(timeout=seconds)`.

A form of `sampler.inspect()` that returns the partial trace that's been produced so far would stilll be nice, but I'll leave that for later.

**Comment by aseyboldt** [comment]
@ricardoV94 If you have a minute, this should be ready for review with the new changes again.

**Comment by ricardoV94** [comment]
Wanna test some of those methods in the new test?

***
Would be nice to setup some docs to show this functionality, but need not be in this PR. The only docs that exist right now are the README :D 

Perhaps a pymc-examples is also a good place.

**Review by ricardoV94 — APPROVED** [review]
This is awesome. The `inspect` thing will also be great in the future!

**Comment by AlexAndorra** [comment]
This is super cool @aseyboldt !!
I just started playing around with this, but I think the `finalize` doesn't exist, so you can't do `trace = sampler.finalize()` to store the trace once the sampler is done.

What I ended up doing is:
```python
compiled_model = nutpie.compile_pymc_model(model)
sampler = nutpie.sample(compiled_model, blocking=False, save_warmup=False, store_unconstrained=False)
idata.extend(sampler.abort())
```
That works, but feels weird from a user perspective.

Is this a bug? I'm happy to open an issue if that's helpful

**Pull request merged**
